import { Geist, Geist_Mono, Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { ThemeProvider } from "./context/ThemeContext";

config.autoAddCss = false;

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Totally Normal Store",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=5",
};

import VisitTracker from "./components/VisitTracker";
import StoreLayout from "./components/StoreLayout";
import QueryProvider from "./components/QueryProvider";

const themeScript = `(function(){
  var d=document.documentElement;
  var t=localStorage.getItem('theme');
  var p=window.matchMedia('(prefers-color-scheme: dark)').matches;
  d.classList.toggle('dark',t==='dark'||(!t&&p));
})();`;

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <ThemeProvider>
          <QueryProvider>
            <AuthProvider>
              <VisitTracker />
              <StoreLayout>{children}</StoreLayout>
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
